main: com.github.tolek.dzialki.Main
version: 1.0.0
name: dzialki
author: tolek_pro
api-version: 1.17

commands:
  dzlist:
  dzcreate:
  dzremove:
  dzinvite:
  dzban:
  dzsetmaxsize:
  dzsetmaxplots:
